### ISSUE TITLE
UBL & CII: v1.3.7 (2021-10-04)/UBL-CR-414

### ISSUE THREAD

**Issue by petredanoiu** [phax/validation#299]
incorrect expression:
<assert id="UBL-CR-414" flag="warning" test="not(cac:PaymentMeans/cbc:InstructionNote)">[UBL-CR-414]-A UBL invoice should not include the PaymentMeans InstructionID</assert>
correct expression must be:
<assert id="UBL-CR-414" flag="warning" test="not(cac:PaymentMeans/cbc:InstructionID)">[UBL-CR-414]-A UBL invoice should not include the PaymentMeans InstructionID</assert>

**Comment by phax** [comment]
@petredanoiu  I don't see a difference between the two expressions....

**Comment by petredanoiu** [comment]
>  [UBL-CR-414]-A UBL invoice should not include the PaymentMeans InstructionID
correct is 
not(cac:PaymentMeans/cbc:InstructionID)
instead of
not(cac:PaymentMeans/cbc:InstructionNote)
see line 799

**Comment by svanteschubert** [comment]
Both elements cbc:InstructionID and cbc:InstructionNote are not part of the syntax Binding of EN16931-3-2

Therefore I would suggest to exchange the line:

    <assert id="UBL-CR-414" flag="warning" test="not(cac:PaymentMeans/cbc:Instruction**Note**)">[UBL-CR-414]-A UBL invoice should not include the PaymentMeans Instruction**ID**</assert>

with two lines:

    <assert id="UBL-CR-414"  flag="warning" test="not(cac:PaymentMeans/cbc:InstructionID)">[UBL-CR-414]-A UBL invoice should not include the PaymentMeans InstructionID</assert>
    <assert id="UBL-CR-414b" flag="warning" test="not(cac:PaymentMeans/cbc:InstructionNote)">[UBL-CR-414b]-A UBL invoice should not include the PaymentMeans InstructionNote</assert>

^^the ID might of course vary
