### ISSUE TITLE
CII: XSLT : BR-CO-08 : always detected 

### ISSUE THREAD

**Issue by jostem** [phax/validation#301]
Hi,

My XML contains 
				<ram:SpecifiedTradeAllowanceCharge>
					<ram:ChargeIndicator>
						<udt:Indicator>**true**</udt:Indicator>
					</ram:ChargeIndicator> 
					<ram:ActualAmount >645.00</ram:ActualAmount>
					<ram:ReasonCode>**AAA**</ram:ReasonCode>
					<ram:Reason>**AAA**</ram:Reason>
				</ram:SpecifiedTradeAllowanceCharge>

And the XSLT rules is  " [BR-CO-08]-Invoice line charge reason code (BT-145) and Invoice line charge reason (BT144) shall indicate the same type of charge reason." is always detected.

in XSLT  ( V1.0 version),  the match for BC-CO-08 is
match="//ram:SpecifiedLineTradeSettlement/ram:SpecifiedTradeAllowanceCharge[ram:ChargeIndicator/udt:Indicator = 'true']"  

in your XSLT  ( V2.0) 
match="//ram:SpecifiedLineTradeSettlement/ram:SpecifiedTradeAllowanceCharge[ram:ChargeIndicator/udt:Indicator = true()]"

XSLT match fonction and rule "BC-CO-08" haven't any matching fields.  ( same for BR-CO-06 et BR-CO-07)

is this a problem or am i missing something ?

thanks

**Comment by oriol** [comment]
The problem with this rule is that it cannot be tested. You cannot compare a text string with a code and check whether they have the same meaning unless the text string is always the same. There can be editing differences in the string or even use of different languages so it is not possible to perform this check, That's why this rule would never automatically fire.

**Comment by jostem** [comment]
I agree that we shouldn't compare a code and a value. However, this is not a personal rule but a CII EN16931 rule and in the "EN16931-CII-validation.xslt" file, the test is carried out on the "Indicator" field. So rule BR-CO-08 is wrong and the test in XSLT "EN16931-CII-validation.xslt" is wrong.

**Comment by jostem** [comment]
it's OK. You an close. thanks

**Comment by jostem** [comment]
My version 1.0 was defected.
