### ISSUE TITLE
Unknown system function: document-uri / Error in expression every $Currency

### ISSUE THREAD

**Issue by alkaan** [phax/validation#302]
Hello,
I'm trying the xslt processing to validate an XML and i obtain this error :
`saxon-xslt -w1 ../../testTrad_20211125082731.xml EN16931-CII-validation.xslt 
Error at xsl:value-of on line 18 of file:/home/jfleuret/Téléchargements/en16931-cii-1.3.7/xslt/EN16931-CII-validation.xslt:
  Error in expression document-uri(/): Unknown system function: document-uri
Transformation failed: Run-time errors were reported
`
tags concerned :
`<xsl:attribute name="document">
          <xsl:value-of select="document-uri(/)" />
        </xsl:attribute>`
if i remove these tags at lines 18 and 174 after i obtain this error :
`saxon-xslt -w1 ../../testTrad_20211125082731.xml EN16931-CII-validation.xslt 
Error at xsl:choose on line 1048 of file:/home/jfleuret/Téléchargements/en16931-cii-1.3.7/xslt/EN16931-CII-validation.xslt:
  Error in expression every $Currency                                  in rsm:SupplyChainTradeTransaction/ram:ApplicableHeaderTradeSettlement/ram:InvoiceCurrencyCode                                 satisfies (                                     count ( rsm:SupplyChainTradeTransaction/ram:ApplicableHeaderTradeSettlement/ram:SpecifiedTradeSettlementHeaderMonetarySummation/ram:TaxTotalAmount[@currencyID=$Currency] ) eq 1 and                                     (//ram:SpecifiedTradeSettlementHeaderMonetarySummation/xs:decimal(ram:GrandTotalAmount) = round(                                      (//ram:SpecifiedTradeSettlementHeaderMonetarySummation/xs:decimal(ram:TaxBasisTotalAmount) +                                      (//ram:SpecifiedTradeSettlementHeaderMonetarySummation/xs:decimal(ram:TaxTotalAmount[@currencyID=$Currency]))) * 10 * 10) div 100)) or                                 (//ram:SpecifiedTradeSettlementHeaderMonetarySummation/xs:decimal(ram:GrandTotalAmount) = (//ram:SpecifiedTradeSettlementHeaderMonetarySummation/xs:decimal(ram:TaxBasisTotalAmount))): Unexpected token $ beyond end of expression
Transformation failed: Run-time errors were reported
`

**Comment by phax** [comment]
Which Saxon version is that commandline tool based upon? Does it support XSLT2?

**Comment by alkaan** [comment]
I searched more precisely and indeed it is only version 8 that supports xslt 2.0
I have SAXON 6.5.5 on linux, 
thanks for your answer, and sorry for the inconvenience

**Comment by phax** [comment]
The latest version of Saxon-HE is 10.6.
The official source is https://www.saxonica.com/download/download_page.xml

Good luck!
