### ISSUE TITLE
BR-CL-19 (Allowance reason code) missing code 105 (which is listed in the codelists)

### ISSUE THREAD

**Issue by MartinForsberg-Ecru** [phax/validation#306]
Code value 105 is listed in the codelist for reason code:
https://ec.europa.eu/digital-building-blocks/wikis/display/DIGITAL/Registry+of+supporting+artefacts+to+implement+EN16931?preview=/467108974/502923554/EN16931%20code%20lists%20values%20v9%20-%20used%20from%202022-03-04.xlsx

But missing in the schematron for UBL

**Comment by phax** [comment]
The CEF list was updated one week ago. So I assume this also affects CII....

**Comment by phax** [comment]
@oriol  this one should also be added to the CII codelist???
