### ISSUE TITLE
CII: BR-CL-10 and BR-CL-26 use conflicting selectors

### ISSUE THREAD

**Issue by phax** [phax/validation#307]
Hi @oriol ,

In CII, BR-CL-10 uses:
```xml
  <rule context="//ram:GlobalID[@schemeID][not(ancestor::ram:SpecifiedTradeProduct)]" flag="fatal">
```
and the selector and BR-CL-26 uses:
```xml
  <rule context="ram:ApplicableHeaderTradeDelivery/ram:ShipToTradeParty/ram:GlobalID[@schemeID]" flag="fatal">
```

They conflict for the `ram:ShipToTradeParty/ram:GlobalID` element.

We think the resolution to this can be to change BR-CL-10 to
```xml
//ram:GlobalID[@schemeID][not(ancestor::ram:SpecifiedTradeProduct) and not(ancestor::ram:ShipToTradeParty)]
```

**Comment by oriol** [comment]
Done as suggested, but shouldn't it be better to just remove BR-CL-26?

**Comment by phax** [comment]
Yes, alternatively a removal of BR-CL-26 would also work I assume

**Comment by oriol** [comment]
Will keep it as is, with the two rules and the new context
