### ISSUE TITLE
Update Card Payment details

### ISSUE THREAD

**Issue by OGlanzmann** [phax/validation#310]
Issue received by Peppol POAC (https://openpeppol.atlassian.net/browse/POACC-421?filter=10240)

"Hi team,

A Service Provider has alerted us that [section 10.7.2 of Peppol BIS Billing - Card Payment](https://docs.peppol.eu/poacc/billing/3.0/bis/#_payment_means_information) may need to be updated.

Only the last 4 digits of a credit card number should be provided in the cac:PaymentMeans/cac:CardAccount/cbc:PrimaryAccountNumberID field for complying with the [Payment Card Industry Data Security Standard (PCI DSS)](https://www.pcisecuritystandards.org/).

The current example in BIS Billing used is “Mandatory, shall be the last 4 to 6 digits of the payment card number”.

Thanks"

POAC Dev team found the issue to origin from BR-51 EN Semantic model, so we forward the issue.

**Comment by oriol** [comment]
In accordance with card payments security standards an invoice should never include a full card primary account number. At the moment PCI Security Standards Council has defined that the first 6 digits and last 4 digits are the maximum number of digits to be shown.

EN16931 BT-87 Usage note (page 54)

**Comment by oriol** [comment]
[BR-51]-The last 4 to 6 digits of the Payment card primary account number (BT-87) shall be present if Payment card information (BG-18) is provided in the Invoice.

string-length(cbc:PrimaryAccountNumberID)&gt;=4 and string-length(cbc:PrimaryAccountNumberID)&lt;=6"

Change the rule to a warning. 

[BR-51]-In accordance with card payments security standards an invoice should never include a full card primary account number. At the moment PCI Security Standards Council has defined that the first 6 digits and last 4 digits are the maximum number of digits to be shown.
