### ISSUE TITLE
Typo in Xpath in for UBL-CR-487

### ISSUE THREAD

**Issue by MartinForsberg-Ecru** [phax/validation#313]
Now:
cac:AllowanceCharge/cac:TaxCategory/cac:TaxScheme/cac:JurisdiccionRegionAddress

Should ne:
cac:AllowanceCharge/cac:TaxCategory/cac:TaxScheme/cac:JurisdictionRegionAddress

**Comment by rkottmann** [comment]
Cause it was hard for me to find the differnece, now with emphasis:

Now:  cac:AllowanceCharge/cac:TaxCategory/cac:TaxScheme/cac:**Jurisdiccion**RegionAddress 

should be: cac:AllowanceCharge/cac:TaxCategory/cac:TaxScheme/cac:**Jurisdiction**RegionAddress
