### ISSUE TITLE
UBL-CR-414 &UBL-CR-681- same test, different err messages

### ISSUE THREAD

**Issue by petredanoiu** [phax/validation#317]
hey

i found this problem

	<assert id="UBL-CR-414" flag="warning" test="not(cac:PaymentMeans/cbc:InstructionNote)">[UBL-CR-414]-A UBL invoice should not include the PaymentMeans InstructionID</assert>
      	<assert id="UBL-CR-681" flag="warning" test="not(cac:PaymentMeans/cbc:InstructionNote)">[UBL-CR-681]-A UBL invoice should not include the PaymentMeans InstructionNote</assert>

i think correct is :
<assert id="UBL-CR-414" flag="warning" test="not(cac:PaymentMeans/cbc:InstructionID)">[UBL-CR-414]-A UBL invoice should not include the PaymentMeans InstructionID</assert>

**Comment by MartinForsberg-Ecru** [comment]
I think this issue was resolved in the latest release.

**Comment by phax** [comment]
@petredanoiu  in which context do you get this error?

**Comment by petredanoiu** [comment]
> I think this issue was resolved in the latest release.

Indeed, resolved in 1.3.8
