### ISSUE TITLE
BR-B-02 rule - incorrect schematron check 

### ISSUE THREAD

**Issue by ConnectingEurope** [phax/validation#318]
The following issue was received into the DIGITAL service desk:

The CEF schematron controls for the tax category even in the case the tax category does not refer to VAT and this causes errors when we try to use Withholding tax (in Italy we have an extension for it). The EN 16931 forsees for a proper VAT treatment of invoices that there shall not be cac:TaxTotal/ cac:TaxSubtotal/cac:TaxCategory/cbc:ID with B and with S in the same invoice, but indeed, the cac:TaxCategory/cbc:ID in cac: WithholdingTaxTotal in not referred to VAT Bâ€ so the schematron check have to be re-arrangend in order not to check the cac:TaxCategory/cbc:ID present in cac:TaxTotal/ cac:TaxSubtotal

Reporter Pietro Palermo, ticket id EINVSD-216

**Comment by phax** [comment]
An example invoice for that particular case would be very helpful

**Comment by pietropalermoIT** [comment]
Here attached an example
[Withholding tax with vat category code B.zip](https://github.com/ConnectingEurope/eInvoicing-EN16931/files/9380760/Withholding.tax.with.vat.category.code.B.zip)

**Comment by pietropalermoIT** [comment]
Let me know if I can help you in understanding the issue. Thank you in advance. Pietro

**Comment by oriol** [comment]
Corrected paths in UBL

**Comment by pietropalermoIT** [comment]
The scematron has been corrected only in test
https://test-docs.peppol.eu/poacc/billing/3.0/
and not in production
https://docs.peppol.eu/poacc/billing/3.0/
