### ISSUE TITLE
Date validation regex is insufficient

### ISSUE THREAD

**Issue by JannickWeisshaupt** [phax/validation#319]
The date validation regex for CII (CII-DT-097)
`
(\d{8})
`
is insufficient as it only checks that there are at least 8 digits.
For example ab20190101 or 1010101001010101001 is a match.
A better expression would be
`
^\s*(\d{8})\s*$
`
which matches exactly 8 digits with only additional white space before and after being allowed.

**Comment by MartinForsberg-Ecru** [comment]
This is built into the CII xsd and not a schematron rule so the issue should rather be send to un/cefact who maintains the schemas.

**Comment by phax** [comment]
Sorry @MartinForsberg-Ecru  I tend to disagree here. The CII D16B XSD just contains this:
```xsd
	<xsd:simpleType name="FormattedDateTimeFormatContentType">
		<xsd:restriction base="xsd:string"/>
	</xsd:simpleType>
	<xsd:complexType name="FormattedDateTimeType">
		<xsd:sequence>
			<xsd:element name="DateTimeString">
				<xsd:complexType>
					<xsd:simpleContent>
						<xsd:extension base="xsd:string">
							<xsd:attribute name="format" type="qdt:FormattedDateTimeFormatContentType"/>
						</xsd:extension>
					</xsd:simpleContent>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
```

whereas the CEN 1.3.8 rules contain this is an explicit rule:

```xml
    <rule context="//udt:DateTimeString[@format = '102']">
      <assert id="CII-DT-097" flag="fatal" test="matches(.,'(\d{8})')">[CII-DT-097] - Date time string with format attribute 102 shall be YYYYMMDD.</assert>
    </rule>
```

**Comment by MartinForsberg-Ecru** [comment]
Oops, sorry. I blame the heat :)
