### ISSUE TITLE
CII-SR-440 for validation X-invoice

### ISSUE THREAD

**Issue by glaejak** [phax/validation#321]
We get the error CII-SR-440 when validating an X-invoice 2.1. This contains two discounts. According to the X-invoice scheme, this is not a problem. However, the EN16931 CII scheme returns the above error.

![grafik](https://user-images.githubusercontent.com/110899993/183621506-98651f2a-d630-4d87-874b-c3dea7c6bdec.png)
![grafik](https://user-images.githubusercontent.com/110899993/183621547-50e51ff3-c334-4cd6-9294-cfe552aaf058.png)

Since the scheme exams contradict each other, I hope to get help here. Can you tell me if there really is a mistake in the exam or if it is our mistake after all?

**Comment by phax** [comment]
This seem to be the rules for BT-147.
And yes, this still applies to the rules 1.3.8

**Comment by oriol** [comment]
The EN states that the BT-147 , the Item price discount, can only be stated once.

**Comment by ozonni** [comment]
i have the same issue, but in my case i have one discount and one additional charge
```
<ram:AppliedTradeAllowanceCharge>
            <ram:ChargeIndicator>
              <udt:Indicator>false</udt:Indicator>
            </ram:ChargeIndicator>
            <ram:ActualAmount>0.8000</ram:ActualAmount>
            <ram:Reason>WAT Reason 10</ram:Reason>
          </ram:AppliedTradeAllowanceCharge>
          <ram:AppliedTradeAllowanceCharge>
            <ram:ChargeIndicator>
              <udt:Indicator>true</udt:Indicator>
            </ram:ChargeIndicator>
            <ram:ActualAmount>0.6000</ram:ActualAmount>
            <ram:Reason>WAT Reason 150</ram:Reason>
          </ram:AppliedTradeAllowanceCharge>
```

**Comment by ozonni** [comment]
@oriol i have the same issue, but in my case i have one discount and one additional charge
```
<ram:AppliedTradeAllowanceCharge>
            <ram:ChargeIndicator>
              <udt:Indicator>false</udt:Indicator>
            </ram:ChargeIndicator>
            <ram:ActualAmount>0.8000</ram:ActualAmount>
            <ram:Reason>WAT Reason 10</ram:Reason>
          </ram:AppliedTradeAllowanceCharge>
          <ram:AppliedTradeAllowanceCharge>
            <ram:ChargeIndicator>
              <udt:Indicator>true</udt:Indicator>
            </ram:ChargeIndicator>
            <ram:ActualAmount>0.6000</ram:ActualAmount>
            <ram:Reason>WAT Reason 150</ram:Reason>
          </ram:AppliedTradeAllowanceCharge>
```

**Comment by phax** [comment]
@ozonni  as Oriol stated above, the EN uses the cardinality 0..1 for field BT-147:
![grafik](https://github.com/user-attachments/assets/fd588fb8-248c-429f-8405-358676de6a29)

Therefore, if this is really a price charge (which is different from the Invoice Lince Charges in BG-28), than you need to combine it into one element.
