### ISSUE TITLE
Update validation artefacts with latest codes

### ISSUE THREAD

**Issue by midran** [phax/validation#324]
EC/DIGITAL has published a new version of the EAS code list and listed new codes for other code lists. The changes are listed in the first tab in the attached spreadsheet.

[EN16931 code lists values v10 - used from 2022-09-21.xlsx](https://github.com/ConnectingEurope/eInvoicing-EN16931/files/9618112/EN16931.code.lists.values.v10.-.used.from.2022-09-21.xlsx)

**Comment by larsroelkerdenker** [comment]
@oriol @midran the change log for ICD says 

> Added   2017, 2018, 2019 and 2020

But this is not correct, 0217, 0218, 0219 and 0220 have been added, this needs to be fixed
