### ISSUE TITLE
Add support for the country code `XK` for Kosovo

### ISSUE THREAD

**Issue by phax** [phax/validation#326]
For Kosovo there is no formal entry in ISO 3166-1 yet and different temporary codes are used (`XK`, `1A`, `1A0`).
However, CEN components currently support only `1A`, while others use `XK` (which is also the current domain for Kosovo).
However, as long as there is no formal assignment in ISO 3166-1, all common temporary codes should be supported on the part of CEN. 

So please include `XK` in addition to `1A` in the country code list.

**Comment by oriol** [comment]
Question for EC, cc @midran, should code XK be added?

**Comment by midran** [comment]
It is not in the latest code list from DIGITAL and therefore shall not be supported in this version of the validation artefacts. Decision on this ticket is pending.

**Comment by oriol** [comment]
Closing this issue. It will be included when it appears in the EC code list.

**Comment by phax** [comment]
Is there a timeplan for adding that to the EC list?
