### ISSUE TITLE
New entries in EAS code list.

### ISSUE THREAD

**Issue by wimkok** [phax/validation#328]
I know the code 0207 voor KVK met vestigingsnummer is approved. When can this EAS code be used

**Comment by oriol** [comment]
It is already in the ICD list, so next release will contain 0207.

**Comment by wimkok** [comment]
Sorry wrong code. The right code is 0217  KvK with establisment number.
![image](https://user-images.githubusercontent.com/7523469/194244657-81651e28-b350-4709-88ef-26de335b6d32.png)
Thanks Dirk for pointing to the right code.

**Comment by oriol** [comment]
Code 0217 is being added in this release.
