### ISSUE TITLE
Include new publication adres for iso6523

### ISSUE THREAD

**Issue by wimkok** [phax/validation#334]
Please make a reference in https://github.com/ConnectingEurope/eInvoicing-EN16931/tree/master/codelist/iso6523 to http://iso6523.info/

This document can be used to update the ICD list. (221 and 222 are missing)

**Comment by dwillekens** [comment]
Agree but i guess most people are interested in http://iso6523.info/icd_list.pdf to have the details on a certain code so this link might be added too.

**Comment by oriol** [comment]
The code lists are maintained by CEF. cc @midran
