### ISSUE TITLE
CII Validation artefact - rounding issue on BR-E-08

### ISSUE THREAD

**Issue by csautereau** [phax/validation#338]
It seems that there is a bug on how CII validation artefact has implemented the BR-E-08 (rounding issue)

Attached an invoice instance in CII and in UBL
CII gives a error on BR-E08, UBL has not

This invoice has a line amount of 4,20 € with Vat category = E
A Document level Allowance has an amount of 1,26 € with Category Tax = E
The VAT breakdown has a instance with category VAT = E and 2,94 € (which is 4,20 -1,26)

So everything is perfect and should be validated.

[F23010007.zip](https://github.com/ConnectingEurope/eInvoicing-EN16931/files/10683591/F23010007.zip)

**Comment by oriol** [comment]
Added slack in BR-E-08
