### ISSUE TITLE
CII - Xsd validation - Coupled schemas - ReasonCode - clm64465AllowanceChargeReasonCode:AllowanceChargeReasonCodeContentType

### ISSUE THREAD

**Issue by benito103e** [phax/validation#339]
Hello,

The list of reasons for a charge (UNTDID 7161) is not taken into account in the CII couple schemas. We apply the list clm64465AllowanceChargeReasonCode:AllowanceChargeReasonCodeContentType which corresponds to UNTDID 5189 no matter if the reasonCode is for a charge or for an allowance.

And so BT-105 and BT-145 data will always raise an error.

Ex. If we pass CII_example3.xml we have XSD violations.

Best regards.

**Comment by MartinForsberg-Ecru** [comment]
Only the decoupled xsds are compliant with EN16931. The following is copied from the CII syntax binding TS16931-3-3

"For syntax binding of EN 16931-1 electronic invoices, the second set of schemas (decoupled) shall be used
to get a fully backwards compatible and stable implementation that enables a system to take future
code list updates into account."

**Comment by benito103e** [comment]
Thanks @MartinForsberg-Ecru for your accurate answer.
