### ISSUE TITLE
CII - missing cardinality check for SpecifiedTradePaymentTerms

### ISSUE THREAD

**Issue by bdewein** [phax/validation#343]
CII syntax allows for 0..n `rsm:SupplyChainTradeTransaction/ram:ApplicableHeaderTradeSettlement/ram:SpecifiedTradePaymentTerms` and  `rsm:SupplyChainTradeTransaction/ram:ApplicableHeaderTradeSettlement/ram:SpecifiedTradePaymentTerms/ram:Description`. 
EN 16931, however, has a restriction of 0..1 on BT-20 "Payment terms" (mapped to `ram:SpecifiedTradePaymentTerms/ram:Description`) and BT-9 "Payment due date" (mapped to `ram:SpecifiedTradePaymentTerms/ram:DueDateDateTime/udt:DateTimeString`).
Thus, there should be a rule to ensure that SpecifiedTradePaymentTerms and Description occur maximum once.

**Comment by oriol** [comment]
Added rules CII-SR-452 and CII-SR-453.
