### ISSUE TITLE
CII - missing cardinality check for ApplicableTradeTax (BG-30)

### ISSUE THREAD

**Issue by bdewein** [phax/validation#349]
CII syntax allows for 0..n `/rsm:CrossIndustryInvoice/rsm:SupplyChainTradeTransaction/ram:IncludedSupplyChainTradeLineItem/ram:SpecifiedLineTradeSettlement/ram:ApplicableTradeTax` . EN 16931 restricts BG-30 (mapped to `/rsm:CrossIndustryInvoice/rsm:SupplyChainTradeTransaction/ram:IncludedSupplyChainTradeLineItem/ram:SpecifiedLineTradeSettlement/ram:ApplicableTradeTax`) to 1..1. Thus, there should be a rule to ensure that an invoice line contains exactly one line VAT information.

**Comment by oriol** [comment]
Added rule CII-SR-454
