### ISSUE TITLE
CII BT-17 and BT-18 checks to be improved

### ISSUE THREAD

**Issue by phax** [phax/validation#353]
BT-17 ("Tender or lot reference") and BT-18 ("Invoiced object identifier") both map to the same elements:
`/rsm:CrossIndustryInvoice/rsm:SupplyChainTradeTransaction/ram:ApplicableHeaderTradeAgreement/ram:AdditionalReferencedDocument/ram:IssuerAssignedID` and
`/rsm:CrossIndustryInvoice/rsm:SupplyChainTradeTransaction/ram:ApplicableHeaderTradeAgreement/ram:AdditionalReferencedDocument/ram:TypeCode`

BT-17 requires a `TypeCode` value of `50`.
BT-18 requires a `TypeCode` value of `130`.

Please add rules, that the respective `TypeCode` values `50` and `130` occur only once.

Please bare in mind, that BT-128 ("Invoice line object identifier") also uses the `TypeCode` value of `130`.

**Comment by oriol** [comment]
Added rules CII-SR-457 and CII-SR-458
