### ISSUE TITLE
CII Missing check on DefinedTradeContact cardinality

### ISSUE THREAD

**Issue by AndreasPvd** [phax/validation#354]
Hello all,

The EN16931 defines that BG-6 (Seller contact) and BG-9 (Buyer contact) have a cardinality of 0..1. UBL matches this definition as it only provides one contact per party. But CII supports multiple contacts (0..n).
The check to prevent the provision of multiple BG-6 and BG-9 is missing in the validation artefacts.

Between CII-SR-226 and CII-SR-227 there should be a rule added like
`<param name="CII-SR-XXX" value="( count(ram:SellerTradeParty/ram:DefinedTradeContact)  &lt;= 1)"/>`

and between CII-SR-255 and CII-SR-256 there should be a rule added like
`<param name="CII-SR-YYY" value="( count(ram:BuyerTradeParty/ram:DefinedTradeContact)  &lt;= 1)"/>`

and definitely the corresponding messages 

```
<assert test="$CII-SR-XXX" flag="fatal" id="CII-SR-XXX">[CII-SR-XXX] - DefinedTradeContact of SellerTradeParty should exist maximum once</assert>
<assert test="$CII-SR-YYY" flag="fatal" id="CII-SR-YYY">[CII-SR-YYY] - DefinedTradeContact of BuyerTradeParty should exist maximum once</assert>
```

Br,
Andreas

**Comment by oriol** [comment]
Added rules CII-SR-455 and CII-SR-456
