### ISSUE TITLE
add missing currency codes

### ISSUE THREAD

**Issue by bdewein** [phax/validation#356]
The following currency codes from ISO 4217 (as listed in the [Registry of Supporting artefacts to implement EN16931](https://ec.europa.eu/digital-building-blocks/wikis/display/DIGITAL/Registry+of+supporting+artefacts+to+implement+EN16931)) are currently not supported and should be added to the currency code list: `STN`, `VES`, `MRU`, `UYW`.

**Comment by midran** [comment]
These codes are listed in the code list but seem to be missing from the validation artefacts.

**Comment by oriol** [comment]
Thanks @bdewein , now corrected.
