### ISSUE TITLE
Bug in CII BR-65

### ISSUE THREAD

**Issue by bdewein** [phax/validation#357]
Currently, BR-65 in CII is contradicting 0..n cardinality of BT-158, assuming an input string in `ram:SpecifiedTradeProduct/ram:DesignatedProductClassification/ram:ClassCode/@listID` check, which causes a type error in case of multiple BT-158 and leads to false positive validation in case of one or more missing list id(s) if at least one is provided (see example invoice). 
Multiple `ram:DesignatedProductClassification/ram:ClassCode/@listID`  should be expected within `ram:SpecifiedTradeProduct` and validation should be updated acordingly.

[01.01a-INVOICE_uncefact.xml.txt](https://github.com/ConnectingEurope/eInvoicing-EN16931/files/12748740/01.01a-INVOICE_uncefact.xml.txt)

**Comment by bdewein** [comment]
@oriol I just discovered this is a duplicate of https://github.com/ConnectingEurope/eInvoicing-EN16931/issues/355. However, I don't think the solution implemented with https://github.com/ConnectingEurope/eInvoicing-EN16931/commit/97511c70051e491d4d1bce638a4b7dacd3429c62 is sufficient. Joining all BT-158-1 into one string will prevent the type error evoked by normalize-string, but is still neglecting BT-158 cardinality of 0..n and thus is preventing correct validation of missing `@listID`s.

As we have recently been receiving multiple support requests in the context of XRechnung (German CIUS of EN16931) regarding this issue, we kindly ask you to consider this for the 1.3.11 release.

**Comment by oriol** [comment]
Hi @bdewein, I think that in this case we need to create a new context to ram:DesignatedProductClassification and check always for the presence of the @listID.

**Comment by bdewein** [comment]
thanks, @oriol
