### ISSUE TITLE
UBL-SR-32

### ISSUE THREAD

**Issue by petredanoiu** [phax/validation#363]
hello

this schematron rule
<rule context="$Tax_subtotal">
    <assert test="$UBL-SR-32" flag="fatal" id="UBL-SR-32">[UBL-SR-32]-VAT exemption reason text shall occur maximum once</assert>
  </rule>

is not in conformable with documentation
according CEN/TS 16931-3-2:2020 (E) :/Invoice/cac:TaxTotal/cac:TaxSubtotal/cac:TaxCategory/cbc:TaxExemptionReason have card. 0..n
if i'm not wrong
to be in conformable with /Invoice/cac:TaxTotal/cac:TaxSubtotal/cac:TaxCategory/cbc:TaxExemptionReasonCode card. 0..1
the rule must be 
<param name="UBL-SR-32" value="(count(cac:TaxCategory/cbc:TaxExemptionReasonCode) &lt;= 1)"/>

am i correct?

**Comment by petredanoiu** [comment]
the rule must be 
<param name="UBL-SR-32" value="(count(cac:TaxCategory/cbc:TaxExemptionReasonCode) &lt;= 1)"/>

am i correct?

**Comment by petredanoiu** [comment]
the rule must be 
[UBL-SR-32]-VAT exemption reason code shall occur maximum once
"UBL-SR-32" value="(count(cac:TaxCategory/cbc:TaxExemptionReasonCode) &lt;= 1)"

**Comment by MartinForsberg-Ecru** [comment]
The cardinality of BT-120, "VAT Exemption Reason text" in the semantic model is 0..1. The UBL XML-schema is more allowing with cardinality is 0..n. The rule checks that only one reason text is used, as that is what the semantic model allows. The syntax binding highlights this discrepancy in the Match-column (CAR-3"). 
![bild](https://github.com/ConnectingEurope/eInvoicing-EN16931/assets/31277932/34fb4a74-d914-4f96-9d45-d1fdab2efe15)

**Comment by petredanoiu** [comment]
hi, martin
thank you for quick reaction
but what about this:
BT-121 card. in semantic model is 0..1 , as in UBL schema (0..1 too), but not schematron rule to validate this
can you explain this to me

many thanks

**Comment by MartinForsberg-Ecru** [comment]
It is expected that the UBL XML Schema would identify a situation where the element is repeated. The XML would not be a valid UBL document and there is no need for a schematron rule.

This goes for all situations where the cardinality of UBL matches the cardinality of the semantic model.

**Comment by petredanoiu** [comment]
and the last one, Martin :
an invoice with multiple lines, different VAT cat.(for example 
2 lines with VAT cat. E, rate 0, each line with different tax exception reason; 
and 
3 lines with VAT cat. S, rate 5, 9 and 19 and different BT-139 (Invoice line allowance reason), each cat. with different rate and different BT-139;
how do i create the xml  element BG-23 VAT break down
can you give me an xml file as example
many thanks

**Comment by MartinForsberg-Ecru** [comment]
The lines with Category S should be summarised per rate and result in one _TaxSubtotal for each rate_. 

The design of the EN16931 only allows for _a single TaxSubtotal_ with category code E. This means that there is no possibility to distinguish the line amounts for different exemption reason. (See rule BR-E-01 https://docs.peppol.eu/poacc/billing/3.0/rules/ubl-tc434/BR-E-01/)

Unfortunately, I don't have time to provide you with more guidance than that.

**Comment by petredanoiu** [comment]
Many thanks, Martin!!Trimis de pe iPhone‑ul meuPe 12 dec. 2023, la 16:15, Martin Forsberg ***@***.***> a scris:﻿
The lines with Category S should be summarised per rate and result in one TaxSubtotal for each rate.
The design of the EN16931 only allows for a single TaxSubtotal with category code E. This means that there is no possibility to distinguish the line amounts for different exemption reason. (See rule BR-E-01 https://docs.peppol.eu/poacc/billing/3.0/rules/ubl-tc434/BR-E-01/)
Unfortunately, I don't have time to provide you with more guidance than that.

**Comment by oriol** [comment]
There is nothing to be done in the rule.
