### ISSUE TITLE
Undocumented and missing changes in v.1.3.11 release

### ISSUE THREAD

**Issue by juskoljo** [phax/validation#366]
Hi,

It seems that there are undocumented and missing changes in version 1.3.11:

- add missing currency codes https://github.com/ConnectingEurope/eInvoicing-EN16931/issues/356
  - Undocumented removal of codes: MRO, STD and VEF
- Typo in rule-text UBL-CR-282, UBL-CR-247 and UBL-CR-183 (UBL) https://github.com/ConnectingEurope/eInvoicing-EN16931/issues/346
  - Rule texts still have CorporationStockAmount instead of CorporateStockAmount
- Typo in rule-text UBL-CR-583, UBL-CR-577 and UBL-CR-572 (UBL) https://github.com/ConnectingEurope/eInvoicing-EN16931/issues/345
  - Rule texts still have BareCodeSymbologyID instead of BarcodeSymbologyID

BR,
Jussi

**Comment by juskoljo** [comment]
Hello, 

Do you know if there will be a hotfix or will those be fixed in the next release?

BR,
Jussi

**Comment by oriol** [comment]
Indeed @juskoljo will fix it next release.

**Comment by oriol** [comment]
Mention to removal of codes MRO, STD and VEF in the currency code list will be added in the release notes.
