### ISSUE TITLE
BR-33 / BR-CO-21 rules validation doesn't work on CII files (OK on UBL files)

### ISSUE THREAD

**Issue by albangiroux** [phax/validation#368]
Hi, 

BR-33 / BR-CO-21 et others rules doesn't work on CII files (it's OK on UBL files)
To reproduce the problem:

1) Download CII_business_example_02.xml (https://github.com/ConnectingEurope/eInvoicing-EN16931/blob/master/cii/examples/CII_business_example_02.xml)

2) Remove <ram:Reason>Rabatt</ram:Reason>

3) Check the file with 
cii/xslt/EN16931-CII-validation.xslt 
or Goto https://www.itb.ec.europa.eu/invoice/upload and validate the file with "CII Invoice XML release 1.3.10" 

You will have 0 error(s), 0 warning(s), 0 message(s)

Note that we have the same problem with 1.3.11 release

**Comment by phax** [comment]
I can confirm with the ecosio validator https://ecosio.com/en/peppol-and-xml-document-validator/ - no error on CII 1.3.10 and 1.3.11
