### ISSUE TITLE
[BR-63] fails if multiple URIUniversalCommunication are present

### ISSUE THREAD

**Issue by JannickWeisshaupt** [phax/validation#369]
The rule [BR-63] fails with the following error
`Error processing schematron validation Schematron rules for EN16931 (CII). Error is A sequence of more than one item is not allowed as the first argument of fn:normalize-space() ("EM", "EM") `
when multiple URIUniversalCommunication are present as follows:
```
                <ram:URIUniversalCommunication>
                    <ram:URIID schemeID="EM">seller@email.de</ram:URIID>
                </ram:URIUniversalCommunication>
                                <ram:URIUniversalCommunication>
                    <ram:URIID schemeID="EM">seller2@email.de</ram:URIID>
                </ram:URIUniversalCommunication>
```
The problematic line seems to be
`normalize-space(rsm:SupplyChainTradeTransaction/ram:ApplicableHeaderTradeAgreement/ram:BuyerTradeParty/ram:URIUniversalCommunication/ram:URIID/@schemeID) != ''`

Here is an example invoice 
[en16931_bug.zip](https://github.com/ConnectingEurope/eInvoicing-EN16931/files/14277791/en16931_bug.zip)

**Comment by csautereau** [comment]
I do not see this as an error.
Buyer electronic address is 0..1 in EN16931
This is the address to which the invoice has to be sent.

You may have confused with Contact email address (which is also 0..1 in fact)
No modification has to be done.

**Comment by JannickWeisshaupt** [comment]
> I do not see this as an error. Buyer electronic address is 0..1 in EN16931 This is the address to which the invoice has to be sent.
> 
> You may have confused with Contact email address (which is also 0..1 in fact) No modification has to be done.

@csautereau Thanks for your opinion. However please try out the example invoice or read my post carefully. 
Hint: Failed validation != Working validation with rejection

**Comment by csautereau** [comment]
I have tried your example.

The schematron gives an error with an invoice with more than one 
 <ram:URIUniversalCommunication>
                    <ram:URIID schemeID="EM">seller@email.de</ram:URIID>
 </ram:URIUniversalCommunication>

On BUYER (and any Party).

If I delete the secund email on your invoice example, validation passes fine. 
Then the error is to provide 2 ram:URIUniversalCommunication, which is not allowed for EN16931.

Now the rule is "
The Buyer electronic  address  (BT-49) shall have a Scheme identifier.
--

If I delete the shemeID="EM" in your example corrected (only 1 ram:URIUniversalCommunication), then schematron rejects with the comment :

[BR-62]-The Seller electronic address (BT-34) shall have a Scheme identifier.
--

Which is normal as your example in fact plays with ram:URIUniversalCommunication of the Seller (and not the buyer)

To finish, If if delete the shemeID="EM" for the Buyer (BT-49, the result is also a mistake with comment 

[BR-63]-The Buyer electronic address (BT-49) shall have a Scheme identifier.
--

Conclusion for me : Schematron is correct on the control of SchemeID presence for Party's Electronic Address (BT-49, BT-34) and also on cardinalities which must be 0..1 (and not multiple)

KR

**Comment by JannickWeisshaupt** [comment]
@csautereau There is a difference between a crashing schematron and a schematron that found errors in the invoice.
I don't care whether the invoice should be rejected or accepted, but the bug is that, because of the buggy rule, the schematron crashes and is unable to generate a correct report.

Try for yourself and add other schematron errors into the invoice, e.g. BR-CO-10. Those should now be reported as well.
Also look at the output for my example invoice. Is the rule stated, which was wrong, i.e. ?

**Comment by oriol** [comment]
The rule is improved with a [1] to check for the first occurrence of the URIUniversalCommunication avoiding crashes. This will not raise any error in case there are more than one URIUniversalCommunication in the document instance. In order to check for this two new rules have been added in the EN16931-CII-Syntax. CII-SR-459 and CII-SR-460 to warn in case more than one URIUniversalCommunication exist.
