### ISSUE TITLE
BT-32 path check missing in BR-AE-02, BR-AE-03, and BR-AE-04 in CII

### ISSUE THREAD

**Issue by bdewein** [phax/validation#371]
All three business rules demand for "the Seller VAT 
Identifier (BT-31), the Seller tax registration identifier (BT-32) and/or the Seller tax 
representative VAT identifier (BT-63)". However, invoices containing BT-32, but not BT-31 or BT-63, do not pass the respective validation in CII (see example files) as check for BT-32  (`//ram:SellerTradeParty/ram:SpecifiedTaxRegistration/ram:ID[@schemeID = 'FC']`) is missing.

[cii-br-ae-02-and-br-ae-03-with-bt-32.txt](https://github.com/ConnectingEurope/eInvoicing-EN16931/files/14572300/cii-br-ae-02-and-br-ae-03-with-bt-32.txt)
[cii-br-ae-02-and-br-ae-04-with-bt-32.txt](https://github.com/ConnectingEurope/eInvoicing-EN16931/files/14572301/cii-br-ae-02-and-br-ae-04-with-bt-32.txt)

**Comment by oriol** [comment]
Added FC in the rules
