### ISSUE TITLE
VAT Category "B" supported even though it is not in the EN

### ISSUE THREAD

**Issue by phax** [phax/validation#378]
The current validation artefacts should imho not support VAT Category "B" as introduced by https://github.com/ConnectingEurope/eInvoicing-EN16931/commit/273cd25 as it is not officially supported in the EN16931-1:2017

**Comment by midran** [comment]
This is because of the Italian A-deviation, EN 16931-1:2017+A1:2019/AC. Code B is allowed in Italy. It is therefore supported in the validation artefacts but not shown in the general code list. The code is therefore officially supported for Italy only.
