### ISSUE TITLE
ISO 4217 HRK / Kuna

### ISSUE THREAD

**Issue by AndreasPvd** [phax/validation#380]
The newest version (13) of the code list distribution still states to be a fully representation of ISO 4217. This is not valid. For example the code HRK / Kuna was added already some time ago which is not part of the official ISO 4217 code list.

The Code list publicaation by Connecting Europe should reflect this by changing "Full list" to "Extended".
I already mentioned this via the offical service desk, which should be used according to the web page. Unfortunately I just received an answer like all processes are working fine and changes are taken into account.

As standardisation and interoperability are objectives of this publication the publication must be accurate.

**Comment by midran** [comment]
This is addressed as part of the code list update by removing HRK. The code was withdrawn by Croatia in 2023-01
