### ISSUE TITLE
Artefacts v1.3.12 (CII) do not check BR-62 / BR-63 correct any more

### ISSUE THREAD

**Issue by AndreasPvd** [phax/validation#381]
With v1.3.12 the possibility to add multiple URIUniversalCommunication in buyer and seller was introduced in the CII validation artefacts.
While doing this BR-62 and BR-63 have been updated to check only the first occurrence to contain a `@schemeID`

This is not correct. BR-62 and BR-63 of EN16931 state that `@schemeID` must always be present. The rules should be updated accordingly.

**Comment by csautereau** [comment]
EN16931 only allow 1 BT-34 or BT-49 (URIUniversalCommunication for seller / Buyer).
How is it possible to have cardinality 0..n if this is what I understand from your post ?

**Comment by AP-G** [comment]
Good question. The restriction in v1.3.11 was removed in v1.3.12

**Comment by oriol** [comment]
As you can see in comment https://github.com/ConnectingEurope/eInvoicing-EN16931/issues/369#issuecomment-2041032831 there were two new rules to control to avoid the repetition of BT-34 and BT-49. These rules are CII-SR-459 and CII-SR-460 that raised warnings. I am changing them to fatal errors.
