### ISSUE TITLE
BR-CO-15 for correct amounts

### ISSUE THREAD

**Issue by JoachimTuchel** [phax/validation#383]
I am using the KOSit Validator 1.5.0 and get a BR-CO-15 Error for this combination of values:
```xml
 <ram:SpecifiedTradeSettlementHeaderMonetarySummation>
                <ram:LineTotalAmount>4600</ram:LineTotalAmount>
                <ram:TaxBasisTotalAmount>4600</ram:TaxBasisTotalAmount>
                <ram:TaxTotalAmount>874</ram:TaxTotalAmount>
                <ram:GrandTotalAmount>5474</ram:GrandTotalAmount>
                <ram:DuePayableAmount>5474</ram:DuePayableAmount>
 </ram:SpecifiedTradeSettlementHeaderMonetarySummation>
```

The error message says: 
[BR-CO-15]-Invoice total amount with VAT (BT-112) = Invoice total amount without VAT (BT-109) + Invoice total VAT amount (BT-110).

Which I would say is 100% correctly fulfilled... I don't see the error... What am I missing? 
(And is this the rigfht place to ask?)

**Comment by bdewein** [comment]
Hi @JoachimTuchel, if this is still an issue: in the above code snippet, `ram:TaxTotalAmount` is missing the attribute `currencyID`, which is required to distinguish BT-110 "Invoice total VAT amount" (the attribute value should match the value of BT-5 "Invoice currency code") from BT-111 "Invoice total VAT amount in accounting currency" (should match BT-6 "VAT accounting currency code"). BR-CO-15 is checking for identity of `ram:TaxTotalAmount/@currencyID` and BT-5 to correctly identify BT-110 for the calculation. Validation fails if there is no match.

For issues with the validator-configuration-xrechnung, you can open a ticket here: https://github.com/itplr-kosit/validator-configuration-xrechnung/issues.

**Comment by oriol** [comment]
Closed. To be followed up in  https://github.com/itplr-kosit/validator-configuration-xrechnung/issues
