### ISSUE TITLE
Invoice Content: Romania Commercial Registaration No. of the Customer (Legal requirment)

### ISSUE THREAD

**Issue by Huebner-Siemenes** [phax/validation#384]
If Romania issues invoices to Romanian customers (based in Romania), the customer's commercial registration number must be indicated on the invoice: (Legal requirement)

[Dok6.docx](https://github.com/user-attachments/files/15822581/Dok6.docx)

**Comment by oriol** [comment]
This is about the Romanian CIUS, not about the EN16931. 

In order to support this requirement, Romania shall create a Romanian CIUS.
