### ISSUE TITLE
Error with a validation with xsl

### ISSUE THREAD

**Issue by amangou-transalis** [phax/validation#385]
Hello,

Trying to test the EDIFACT validation however, the encounter the following error: 
![image](https://github.com/ConnectingEurope/eInvoicing-EN16931/assets/173378294/af3b41e8-9a02-4e17-8248-f5b36cceedb9)

Please can you help us to find out on this? 

Thanks,
Andromachi

**Comment by phax** [comment]
Xalan only supports XSLT1. You must use an XSLT2 engine like Saxon to make it work...
