### ISSUE TITLE
codes_validation_BR-CL-23_weakness

### ISSUE THREAD

**Issue by petredanoiu** [phax/validation#388]
hey

this @unitCode
 <cbc:InvoicedQuantity unitCode="XTN&#xD;&#xA;">19800.00</cbc:InvoicedQuantity>
 is not a value according to the UN/ECE Recommendation 20 with Rec 21 extension
but 
schematron validation is successful.

seems to be a weakness in the evaluation of rule BR-CL-23.
It's correct?
if so, what should be done to remove the problem?

thank you

**Comment by petredanoiu** [comment]
hey ...again
in fact this is the value for unitCode in xml that pass from validation
<cbc:InvoicedQuantity unitCode="XTN&#xD;&#xA;">19800.00</cbc:InvoicedQuantity>

**Comment by petredanoiu** [comment]
![image](https://github.com/user-attachments/assets/212f175a-2f8a-440f-8846-aab711f7948d)

**Comment by midran** [comment]
Code TN exists in recommedation 21 and is the unit for a tin. According to specification, when recommendation 20 is extended with recommendation 21 then the rec21 codes shall be prefixed with an X (point 2a in the intro to rec 20). Hence the code XTN. Not an error.

**Comment by phax** [comment]
The problem is the `&#xD;&#xA;` afterwards which corresponds to `\r\n` or `CR`+`LF`.
I assume it is stripped in `normalize-space` or so....
