### ISSUE TITLE
Chat community

### ISSUE THREAD

**Issue by leonardehrenfried** [phax/validation#389]
[Sorry for the spam]

As you are probably aware e-invoices are becoming mandatory in Germany but I'm very confused about all these specifications (EN 16931, XRechnung, Factur-X, Finnvoice, PEPPOL BIS, UBL, CII ...) and to what degree they are supposed to be compatible with each other.

For this reason I'm starting a chat room on Matrix (open source chat network) where I would like to build a community of people interested in this topic:
https://matrix.to/#/#e-invoicing:matrix.org (you can join with a Github account).

I would love it if the people that are contributing to this project would be interested in joining there.

Thanks for reading and sorry for bothering you if you're not interested.

@oriol @phax @AndreasPvd @zpatkai @svanteschubert @SiwMeckelborg @yildiraykabak

**Comment by phax** [comment]
Sorry, I am already running a Slack channel on these topics - I don't have the resources to contribute to another community. But feel free to ping me for addition to the Slack channel...

**Comment by midran** [comment]
Please do not use this channel for these kind of announcements even though they are relevant for eInvoicing. The ability to keep this as an open channel without requiring granting access is dependent on it being used for issues relating specifically to the maintenance of the validation artefacts.

**Comment by leonardehrenfried** [comment]
I understand.

**Comment by phax** [comment]
@midran  you could open the "Discussion" forum for this repository, so that people don't need to abuse the Issues for these things....

**Comment by midran** [comment]
@phax the Discussion forum has been open for quite some time but noone has started a discussion.

**Comment by phax** [comment]
Because it is not publically visible. At least I don't see it:
![grafik](https://github.com/user-attachments/assets/06bc8109-ae97-4552-b0cb-1729f84cd8d8)

In another project I see the Discussions element:
![grafik](https://github.com/user-attachments/assets/5953c13f-b5fc-48a0-9228-4658fca08ad1)

So I assume it is something in the GitHub settings

**Comment by midran** [comment]
Yes and seems to be related to access levels. I can see it but it was not marked as active. I have now made it active. @phax try again.

**Comment by phax** [comment]
@midran  thank you, now I can see it. So @leonardehrenfried you have a way forward :)
