### ISSUE TITLE
Update validation artafacts with Nov 24 codes

### ISSUE THREAD

**Issue by midran** [phax/validation#390]
Update rules in validation artefacts with code changes made in Fall 24. Take notice of following

- [x] Verify if older updates to currency are implemented. Specially for VES and VEF and for SLL. #373

**Comment by midran** [comment]
Code lists were updated by EC/DIGITAL on 2024-10-01 and made available on https://ec.europa.eu/digital-building-blocks/sites/display/DIGITAL/Registry+of+supporting+artefacts+to+implement+EN16931. 

Following changes need to be made to the validation artefacts.

- [x] ISO 4217 — Currency codes: Add VED and ZWG. Remove HRK, verify removal of SLL.
- [x] ISO/IEC 6523 — Identifier scheme code, ICD: Add 0231 to 0238 (8 codes)
- [x] CEF EAS — Electronic address scheme identifier, EAS: Add 0177 and 0235 (2 codes)
- [x] CEF VATEX — VAT exemption reason code, VATEX: Add VATEX-EU-144, VATEX-EU-146-1E, VATEX-EU-159 (3 codes)

**Comment by svanteschubert** [comment]
@midran Please double-check the download link of 
**Full listing of the code lists as used in EN16931 - version 14.0**
It seems the VATEX Code list was duplicated there.
Thanks in advance, Svante

**Comment by svanteschubert** [comment]
PS: The "Regular release schedule" table could be updated to this release and Spring release 2025.🤗

**Comment by midran** [comment]
> @midran Please double-check the download link of **Full listing of the code lists as used in EN16931 - version 14.0** It seems the VATEX Code list was duplicated there. Thanks in advance, Svante

Fixed, thanks for notifying
