### ISSUE TITLE
Problem with quantities and decimal places

### ISSUE THREAD

**Issue by AlgoLinz** [phax/validation#411]
Hi, 
I am using the NuGet package ZugFerd-csharp version 16.0.3. 

My client deals with wood, and therefore the quantities must be specified with three decimal places. When I create an invoice with a single item:
- Price / m³ = 520 EUR
- Quantity = 15,619
- Tax = 19%
- Netto amount = 8121,88 EUR
- tax amount = 1543,16 EUR
- Brutto amount = 9665,94 EUR

then my XML file looks like this:
```xml
      <ram:SpecifiedLineTradeAgreement>
        <ram:NetPriceProductTradePrice>
          <ram:ChargeAmount>8122.40</ram:ChargeAmount>
        </ram:NetPriceProductTradePrice>
      </ram:SpecifiedLineTradeAgreement>
```

In the element ChargeAmount, the total net amount is present (it should be the net price per unit, which is 520). Consequently, the remaining calculations, such as:

```xml
        <ram:SpecifiedTradeSettlementLineMonetarySummation>
          <ram:LineTotalAmount>126871.89</ram:LineTotalAmount>
        </ram:SpecifiedTradeSettlementLineMonetarySummation>
```
is wrong.

However, if the quantity is specified without decimal places (e.g., 15 or 50 or ...), then the XML section looks correct. In the element ChargeAmount, the net price per unit is specified.

Could it be that the library in version 16.0.3 has a bug in this area?

Thank you

**Comment by phax** [comment]
Please ask your questions in English - thank you. Automatic translators like `deepl.com` or Google Translate might help you if needed.

**Comment by AlgoLinz** [comment]
@phax => next time? or you need it now?

**Comment by phax** [comment]
Well, to be honest did you already ask the guys of your NuGet package ZugFerd-csharp first?
We cannot answer any solution-specific questions here....

**Comment by AlgoLinz** [comment]
Hi @phax,

hmmm, yes. That's correct. Sorry, I posted my issue on the wrong platform. It should be posted on the ZugFerd-csharp platform.
Obviously, it's time for a vacation.

I am closing the ticket.

Best regards

**Comment by phax** [comment]
@AlgoLinz  happy vacation - I get you ;-)
